
project_id = "tlluqspuyjxfsrzpqked"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://tlluqspuyjxfsrzpqked.supabase.co"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54323

[functions.sync-users]
verify_jwt = false
